### PR TITLE
Let me search anything beforehand without selecting

### PR DESCRIPTION
**Pull request by jfromaniello**
I would like to be able to search anything in dash without having to select the text, sometimes I need to look an API before I actually write the code.

This is my proposed change, 

regards

### CODE REVIEW

**Comment by farcaller** [comment]
I've reconsidered this, and if you want to follow up, please rebase it.

**Comment by ryanpcmcquen** [comment]
@jfromaniello, would you mind rebasing this?

**Comment by jfromaniello** [comment]
This is 5 years old 😂, almost the age of my youngest! I am not longer using Sublime and I don't remember exactly the details about this, wont be able to try it out.

I still use Dash.app a lot but I just cmd+tab to it.

**Comment by ryanpcmcquen** [comment]
@jfromaniello, I rebased your PR: https://github.com/farcaller/DashDoc/pull/65

Thanks for your work!

**Comment by farcaller** [comment]
Fixed in #65.

**Pull request closed without merging**
