### PR TITLE
Added Linux support - using xdg-open

### PR DESCRIPTION
**Pull request by madblobfish**
This works on my Ubuntu 14.04 don't know about others

### CODE REVIEW

**Comment by farcaller** [comment]
Can you add a readme note explaining the dependencies? (xdg-open)

**Comment by madblobfish** [comment]
Sure.
Also tested on Fedora, works.

**Comment by madblobfish** [comment]
Updated the Readme.
Is this good?

**Comment by farcaller** [comment]
LGTM, thanks.

**Pull request merged**
